SET @HOUR := -1;

SELECT (@HOUR := @HOUR + 1) as HOUR,
      (SELECT COUNT(DATETIME)
        FROM ANIMAL_OUTS
        WHERE @HOUR = HOUR(DATETIME)) as COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
ORDER BY HOUR ASC